2025-05-19 03:56:52 ServerProcess [INFO] Server Process ID: 77153
2025-05-19 03:56:52 DiagnosticsApp [ERROR] Action executor MetricsSnapshot is not available.
2025-05-19 03:56:52 DiagnosticsApp [INFO] Starting WSO2 Diagnostics Tool
2025-05-19 03:56:52 ServerInfo [INFO] Update level: 7
2025-05-19 03:56:52 DiagnosticsApp [INFO] Server name: WSO2 Micro Integrator
2025-05-19 03:56:52 DiagnosticsApp [INFO] Version: 4.4.0
2025-05-19 03:56:52 DiagnosticsApp [INFO] Update Level: 7
2025-05-19 03:56:52 DiagnosticsApp [INFO] Java Version: 21.0.7
2025-05-19 03:56:52 DiagnosticsApp [INFO] Java Home: /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home
2025-05-19 03:56:52 DiagnosticsApp [INFO] OS Name: Mac OS X
2025-05-19 03:56:52 DiagnosticsApp [INFO] OS Version: 15.4.1
2025-05-19 03:56:52 DiagnosticsApp [INFO] OS Architecture: aarch64
2025-05-19 03:56:52 DiagnosticsApp [INFO] Diagnostic App Home: /Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool
2025-05-19 03:56:52 DiagnosticsApp [INFO] Listening to : ../repository/logs/wso2error.log
2025-05-19 03:56:52 LogWatcher [INFO] Initiating LogWatcher for file: /Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool/../repository/logs/wso2error.log
2025-05-19 03:56:52 DiagnosticsApp [INFO] Initiating CPUWatcher with interval: 5 retry count: 2 threshold: 80
2025-05-19 03:56:52 DiagnosticsApp [INFO] Initiating MemoryWatcher with interval: 5 retry count: 2 threshold: 80
2025-05-19 03:56:52 DiagnosticsApp [INFO] Initiated Custom Watcher: org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzer
2025-05-19 03:56:52 TrafficAnalyzer [INFO] LastFifteenSecondsRequests Traffic Analyzer is enabled with window size: 100, interval: 15, delay: 4
2025-05-19 03:56:52 TrafficAnalyzer [INFO] LastMinuteRequests Traffic Analyzer is enabled with window size: 100, interval: 60, delay: 1
2025-05-19 03:56:52 DiagnosticsApp [INFO] Started Custom Watcher: org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzer
2025-05-19 04:08:22 TrafficAnalyzerRunnable [INFO] Attribute Last15SecondRequests of type https-listener increased more than the threshold, old value: 2, new value: 4, threshold: 3.5
2025-05-19 08:42:04 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(RMIConnectionImpl_Stub.java:279) ~[?:?]
	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:95) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:61) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 14 more
2025-05-19 08:42:04 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:65) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:42:04 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:69) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:42:04 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:73) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:42:05 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(RMIConnectionImpl_Stub.java:279) ~[?:?]
	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:95) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 14 more
2025-05-19 08:42:05 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(RMIConnectionImpl_Stub.java:279) ~[?:?]
	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:95) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 14 more
2025-05-19 08:42:05 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 1
2025-05-19 08:42:05 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:42:05 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:42:05 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 2
2025-05-19 08:42:05 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:42:05 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:42:05 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 3
2025-05-19 08:42:05 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:57:18 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:57:23 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:57:23 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:61) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:57:23 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:65) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:57:23 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:69) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:57:23 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:73) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:57:23 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:61) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:57:23 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:65) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:57:23 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:69) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 08:57:23 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:73) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:12:15 ThreadDumper [INFO] Thread dump execution is completed for 77153, thread dump count: 5, delay: 2000ms
2025-05-19 09:12:15 MemoryWatcher [ERROR] Action executor MetricsSnapshot is not available.
2025-05-19 09:12:15 ServerInfo [INFO] Update level: 7
2025-05-19 09:12:15 ServerInfo [INFO] ServerInfo executed successfully.
2025-05-19 09:12:15 ZipFileExecutor [INFO] Zipping the folder at /Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool/temp/2025-05-19_08:42:05.439
2025-05-19 09:12:16 ZipFileExecutor [INFO] Diagnosis Dumped in :/Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool/data/77153_2025-05-19_08:42:05.439.zip
2025-05-19 09:12:16 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:12:16 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 1
2025-05-19 09:12:16 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:12:16 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 2
2025-05-19 09:12:16 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:12:16 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 3
2025-05-19 09:12:19 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:30:14 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:30:17 ThreadDumper [INFO] Thread dump execution is completed for 77153, thread dump count: 5, delay: 2000ms
2025-05-19 09:30:17 MemoryWatcher [ERROR] Action executor MetricsSnapshot is not available.
2025-05-19 09:30:17 ServerInfo [INFO] Update level: 7
2025-05-19 09:47:08 ServerInfo [INFO] ServerInfo executed successfully.
2025-05-19 09:47:08 ZipFileExecutor [INFO] Zipping the folder at /Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool/temp/2025-05-19_09:12:16.033
2025-05-19 09:47:08 ZipFileExecutor [INFO] Diagnosis Dumped in :/Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool/data/77153_2025-05-19_09:12:16.033.zip
2025-05-19 09:47:08 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:47:08 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 1
2025-05-19 09:47:08 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:47:08 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 2
2025-05-19 09:47:10 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:47:10 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:61) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:47:10 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:47:10 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 3
2025-05-19 09:47:10 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:65) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:47:10 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:69) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:47:10 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:73) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:57:42 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectIOException: Exception creating connection to: 192.168.1.2; nested exception is: 
	java.net.SocketException: Network is unreachable
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:637) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 09:57:48 ThreadDumper [INFO] Thread dump execution is completed for 77153, thread dump count: 5, delay: 2000ms
2025-05-19 09:57:48 MemoryWatcher [ERROR] Action executor MetricsSnapshot is not available.
2025-05-19 09:57:48 ServerInfo [INFO] Update level: 7
2025-05-19 09:57:48 ServerInfo [INFO] ServerInfo executed successfully.
2025-05-19 09:57:48 ZipFileExecutor [INFO] Zipping the folder at /Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool/temp/2025-05-19_09:47:10.645
2025-05-19 09:57:48 ZipFileExecutor [INFO] Diagnosis Dumped in :/Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool/data/77153_2025-05-19_09:47:10.645.zip
2025-05-19 10:00:17 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:01:32 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:61) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:02:47 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:02:47 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 1
2025-05-19 10:04:02 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:65) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:05:17 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:06:32 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:69) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:07:47 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:07:47 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 2
2025-05-19 10:09:02 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:73) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:10:17 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:11:32 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:61) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:12:47 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:12:47 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 3
2025-05-19 10:12:58 ThreadDumper [INFO] Thread dump execution is completed for 77153, thread dump count: 5, delay: 2000ms
2025-05-19 10:12:58 MemoryWatcher [ERROR] Action executor MetricsSnapshot is not available.
2025-05-19 10:12:58 ServerInfo [INFO] Update level: 7
2025-05-19 10:12:58 ServerInfo [INFO] ServerInfo executed successfully.
2025-05-19 10:12:58 ZipFileExecutor [INFO] Zipping the folder at /Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool/temp/2025-05-19_10:12:47.937
2025-05-19 10:12:58 ZipFileExecutor [INFO] Diagnosis Dumped in :/Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool/data/77153_2025-05-19_10:12:47.937.zip
2025-05-19 10:14:03 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:65) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:15:18 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:16:33 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:69) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:17:48 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:17:48 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 1
2025-05-19 10:19:03 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:73) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:20:18 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:21:33 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:61) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:22:48 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:65) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:24:03 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:24:03 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 2
2025-05-19 10:26:33 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:69) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:27:48 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:29:03 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:73) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:30:18 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getMemoryUsage(JMXDataRetriever.java:56) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.MemoryWatcher.run(MemoryWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:30:18 MemoryWatcher [INFO] Heap usage is above threshold. Heap usage: 100.0%, Retry count: 3
2025-05-19 10:30:28 ThreadDumper [INFO] Thread dump execution is completed for 77153, thread dump count: 5, delay: 2000ms
2025-05-19 10:30:28 MemoryWatcher [ERROR] Action executor MetricsSnapshot is not available.
2025-05-19 10:30:28 ServerInfo [INFO] Update level: 7
2025-05-19 10:30:29 ServerInfo [INFO] ServerInfo executed successfully.
2025-05-19 10:30:29 ZipFileExecutor [INFO] Zipping the folder at /Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool/temp/2025-05-19_10:30:18.357
2025-05-19 10:30:29 ZipFileExecutor [INFO] Diagnosis Dumped in :/Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool/data/77153_2025-05-19_10:30:18.357.zip
2025-05-19 10:31:33 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:61) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:32:48 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:34:03 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getCpuUsage(JMXDataRetriever.java:51) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.watchers.CPUWatcher.run(CPUWatcher.java:58) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:35:18 JMXDataRetriever [ERROR] Error while getting JMX data
java.rmi.ConnectException: Connection refused to host: 192.168.1.2; nested exception is: 
	java.net.ConnectException: Operation timed out
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:625) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204) ~[?:?]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134) ~[?:?]
	at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2106) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getConnection(JMXDataRetriever.java:125) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getJmxData(JMXDataRetriever.java:92) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.diagnostics.utils.JMXDataRetriever.getIntAttributeValue(JMXDataRetriever.java:47) ~[runtime-diagnostics-tool-1.1.1.jar:1.1.1]
	at org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzerRunnable.run(TrafficAnalyzerRunnable.java:65) ~[org.wso2.carbon.mediation.diagnostics-4.7.244.jar:4.7.244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.net.ConnectException: Operation timed out
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:589) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:578) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.net.Socket.connect(Socket.java:686) ~[?:?]
	at java.net.Socket.<init>(Socket.java:555) ~[?:?]
	at java.net.Socket.<init>(Socket.java:324) ~[?:?]
	at sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40) ~[?:?]
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[?:?]
	... 18 more
2025-05-19 10:56:59 ServerProcess [INFO] Server Process ID: 97915
2025-05-19 10:56:59 DiagnosticsApp [ERROR] Action executor MetricsSnapshot is not available.
2025-05-19 10:56:59 DiagnosticsApp [INFO] Starting WSO2 Diagnostics Tool
2025-05-19 10:56:59 ServerInfo [INFO] Update level: 7
2025-05-19 10:56:59 DiagnosticsApp [INFO] Server name: WSO2 Micro Integrator
2025-05-19 10:56:59 DiagnosticsApp [INFO] Version: 4.4.0
2025-05-19 10:56:59 DiagnosticsApp [INFO] Update Level: 7
2025-05-19 10:56:59 DiagnosticsApp [INFO] Java Version: 21.0.7
2025-05-19 10:56:59 DiagnosticsApp [INFO] Java Home: /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home
2025-05-19 10:56:59 DiagnosticsApp [INFO] OS Name: Mac OS X
2025-05-19 10:56:59 DiagnosticsApp [INFO] OS Version: 15.4.1
2025-05-19 10:56:59 DiagnosticsApp [INFO] OS Architecture: aarch64
2025-05-19 10:56:59 DiagnosticsApp [INFO] Diagnostic App Home: /Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool
2025-05-19 10:56:59 DiagnosticsApp [INFO] Listening to : ../repository/logs/wso2error.log
2025-05-19 10:56:59 LogWatcher [INFO] Initiating LogWatcher for file: /Users/samindu/Workspace/integration-project/wso2-mi/diagnostics-tool/../repository/logs/wso2error.log
2025-05-19 10:56:59 DiagnosticsApp [INFO] Initiating CPUWatcher with interval: 5 retry count: 2 threshold: 80
2025-05-19 10:56:59 DiagnosticsApp [INFO] Initiating MemoryWatcher with interval: 5 retry count: 2 threshold: 80
2025-05-19 10:56:59 DiagnosticsApp [INFO] Initiated Custom Watcher: org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzer
2025-05-19 10:56:59 TrafficAnalyzer [INFO] LastFifteenSecondsRequests Traffic Analyzer is enabled with window size: 100, interval: 15, delay: 4
2025-05-19 10:56:59 TrafficAnalyzer [INFO] LastMinuteRequests Traffic Analyzer is enabled with window size: 100, interval: 60, delay: 1
2025-05-19 10:56:59 DiagnosticsApp [INFO] Started Custom Watcher: org.wso2.carbon.diagnostics.trafficanalyzer.TrafficAnalyzer
2025-05-19 11:08:20 TrafficAnalyzerRunnable [INFO] Attribute Last15SecondRequests of type https-listener increased more than the threshold, old value: 2, new value: 4, threshold: 3.2761423749153966
2025-05-19 11:38:40 TrafficAnalyzerRunnable [INFO] Attribute Last15SecondRequests of type https-listener increased more than the threshold, old value: 0, new value: 5, threshold: 3.9790496217739157
2025-05-19 11:40:25 TrafficAnalyzerRunnable [INFO] Attribute Last15SecondRequests of type https-listener increased more than the threshold, old value: 2, new value: 5, threshold: 4.487038598169708
